#!/usr/bin/env bash
# Install nginx web server

# update te operating system and install nginx 
apt-get -y update && apt-get install -y nginx

# allow incomming trafic on default NGINX HTTP
ufw allow 'Nginx HTTP'

# make sure that directory exists
mkdir -p /var/www/html && chmod -R 755 /var/www

# write the string hello world! in index.html file
echo 'Hello World!' > /var/www/html/index.html

# change setting and listen to port 80 via tee command
tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# restart nginx to save the changes
sudo service nginx restart
