#!/usr/bin/env bash
# script installs and configures HAproxy on a new Ubuntu machine

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 54.237.41.174:80 check
    server web-02 54.175.224.162:80 check
EOF'

#sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart
