#!/usr/bin/env bash
# Bash script that: Creates the file /var/run/myscript.pid containing its PID

sudo bash -c 'echo $$ > /var/run/myscript.pid'
cleanup() {
    rm -f /var/run/myscript.pid
    exit
}

trap 'cleanup' EXIT
trap "echo 'I hate the kill command';exit" SIGTERM
trap "echo 'Y U no love me?!';exit" SIGINT

while true; do
    echo "To infinity and beyond"
	sleep 1
done
