#!/usr/bin/env bash
# Bash script that: Creates the file /var/run/myscript.pid containing its PID
cleanup() {
    rm -f /var/run/myscript.pid
    exit
}

trap "cleanup" SIGTERM SIGQUIT

echo $$ > /var/run/myprocess.pid
trap "echo 'I hate the kill command';exit" SIGTERM
trap "echo 'Y U no love me?!';exit" SIGINT

while true; do
    echo "To infinity and beyond"
	sleep 1
done
